apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: adservice
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: gcr.io/google-samples/microservices-demo/adservice:v0.7.0
        ports:
          - containerPort: 8080
            name: h2c
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
        env:
        - name: DISABLE_PROFILER
          value: "1"