apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cartservice
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: gcr.io/google-samples/microservices-demo/cartservice:v0.7.0
        args: ["-p", "$(PORT)"]
        ports:
          - containerPort: 7070
            name: h2c
        env:
          - name: REDIS_ADDR
            value: "redis-cart:6379"
          # - name: LISTEN_ADDR
          #   value: "0.0.0.0"
          - name: DISABLE_PROFILER
            value: "1"     
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
#            value: "10.5.22.11"