apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: checkoutservice
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.2.3
        ports:
          - containerPort: 8080
            name: h2c
        env:
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice.cloud-run-sandbox.svc.cluster.local:80"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice.cloud-run-sandbox.svc.cluster.local:80"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice.cloud-run-sandbox.svc.cluster.local:80"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice.cloud-run-sandbox.svc.cluster.local:80"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice.cloud-run-sandbox.svc.cluster.local:80"
          - name: CART_SERVICE_ADDR
            value: "cartservice.cloud-run-sandbox.svc.cluster.local:80"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi