apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: currencyservice
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: gcr.io/google-samples/microservices-demo/currencyservice:v0.7.0
        ports:
          - containerPort: 7000
            name: h2c
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        env:
        - name: DISABLE_PROFILER
          value: "1"