apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: gcr.io/google-samples/microservices-demo/frontend:v0.7.0
        # ports:
        #   - containerPort: 8080
        #     name: h2c
        env:
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice.cloud-run-sandbox.svc.cluster.local:80"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice.cloud-run-sandbox.svc.cluster.local:80"
          - name: CART_SERVICE_ADDR
            value: "cartservice.cloud-run-sandbox.svc.cluster.local:80"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "recommendationservice.cloud-run-sandbox.svc.cluster.local:80"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice.cloud-run-sandbox.svc.cluster.local:80"
          - name: CHECKOUT_SERVICE_ADDR
            value: "checkoutservice.cloud-run-sandbox.svc.cluster.local:80"
          - name: AD_SERVICE_ADDR
            value: "adservice.cloud-run-sandbox.svc.cluster.local:80"
          - name: DISABLE_PROFILER
            value: "1" 
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi           