apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: recommendationservice
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.2.3
        ports:
          - containerPort: 8080
            name: h2c
        env:
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice.cloud-run-sandbox.svc.cluster.local:80"
        resources:
          requests:
            cpu: 100m
            memory: 220Mi
          limits:
            cpu: 200m
            memory: 450Mi